name: ankara_2_barosu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  table_calendar: ^3.1.2
  webview_flutter: ^4.10.0
  async: 2.12.0 # flutter_test ile uyumlu sürüm
  fake_async: 1.3.2
  material_color_utilities: 0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  leak_tracker: 10.0.8
  vm_service: 14.3.1

flutter:
  uses-material-design: true